### ISSUE TITLE
How to sign in with a phone number ?

### ISSUE THREAD

**Issue by sallsabil** [yaroslavche/phptdlib#10]
Does your extension has this ability to sign in with a phone number ?

**Comment by yaroslavche** [comment]
At the moment - no (and I don't know if this is possible)
This is a simple wrapper over td_json_client_* functions.
It will help me a lot, if I know what kind of request it is necessary to send, that would make a sign in with a phone number.

**Comment by sallsabil** [comment]
I think sign in is related to https://core.telegram.org/mtproto

**Comment by sallsabil** [comment]
from php don't I have access to this ?
https://github.com/tdlib/td/tree/master/td/mtproto

**Comment by yaroslavche** [comment]
I'll definitely check it out

**Comment by sallsabil** [comment]
Thank you

**Comment by yaroslavche** [comment]
#9
