### ISSUE TITLE
/usr/include/phpcpp/throwable.h:29:1: error: expected class-name before ‘{’ token

### ISSUE THREAD

**Issue by xzwjz2** [yaroslavche/phptdlib#100]
**PROBLEM:** trying to make in Debian 11, PHP 7.4 got the errors:

[ 97%] Building CXX object CMakeFiles/tdlib.dir/include/TDLib/BaseJsonClient.cpp.o
In file included from /usr/include/phpcpp.h:38,
                 from /opt/phptdlib/include/TDLib/BaseJsonClient.hpp:4,
                 from /opt/phptdlib/include/TDLib/BaseJsonClient.cpp:1:
/usr/include/phpcpp/throwable.h:29:1: error: expected class-name before ‘{’ token
   29 | {
      | ^
/usr/include/phpcpp/throwable.h: In constructor ‘Php::Throwable::Throwable(const string&)’:
/usr/include/phpcpp/throwable.h:43:63: error: expected class-name before ‘(’ token
   43 |     Throwable(const std::string &message) : std::runtime_error(message) {}
      |                                                               ^
/usr/include/phpcpp/throwable.h:43:63: error: expected ‘{’ before ‘(’ token
make[2]: *** [CMakeFiles/tdlib.dir/build.make:95: CMakeFiles/tdlib.dir/include/TDLib/BaseJsonClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:443: CMakeFiles/tdlib.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**SOLUTION:**
Edit file _/usr/include/phpcpp/throwable.h_
and add the line:
_#include \<stdexcept\>_

**Comment by yaroslavche** [comment]
Hi. In general I agree about the exception. This is a really good case. But I don't know how to reproduce.

**Comment by xzwjz2** [comment]
Hi, Yaroslav,

I found the error in a fresh Debian 11 virtual machine in Azure, with a fresh LAMP with php 7.4, and following your installation instruccions. 
I tried the solution I mentioned and it worked.

**Comment by yaroslavche** [comment]
This is PHP-CPP issue, and an example how to fix if you would face that. I will close this issue.
