### ISSUE TITLE
SendMessage Issue

### ISSUE THREAD

**Issue by bugbaal** [yaroslavche/phptdlib#108]
I don't know why sometimes the message is not delivered.
I check the response and I get the right json which shows no difference between that is sent and what remains suspended.
When I try to send another one, just now it sends the previous messages plus the new one.
So, it seems like they stay in the box and when prompted by a new message they wake up and go all together.
I would like to know if there is a way to push all messages or if I miss something to send message in the correct way.
Thanks

**Comment by yaroslavche** [comment]
Hi.
This extension don't perform any additional code. It provides only the wrapper for tdlib json client functions. So, if you're facing some issues with them - please check tdlib documentation.
Can't help with this, sorry.

**Comment by bugbaal** [comment]
And I did, and he says to manage the updateMessageSendSucceeded update.
Don't know how to use it with your library.
Because when I check the response from sendMessage it is always messageSendingStatePending even if it send the message correctly or not.

**Comment by yaroslavche** [comment]
`td_json_client_receive`
If you're using `query`, then it always returns a response by extra. But you can get all responses before that response.

**Comment by bugbaal** [comment]
yes, i'm using query to send the "sendmessage" command.
Maybe I found a solution.
1. Send the sendmessage by ->query().
2. query response with body message and it always says that status is: messageSendingStatePending
3. Now I add and call ->receive() method
4. Receive command send me all updates and I keep it alive until I receive the status updateMessageSendSucceeded.
I was using the ->getReceivedResponses() that doesn't work for me. It is always null
Thank you for supporting me
