### ISSUE TITLE
How do I upgrade tdlib from version 1.8.10 to the latest 1.8.25?

### ISSUE THREAD

**Issue by kubsite1** [yaroslavche/phptdlib#117]
How do I upgrade tdlib from version 1.8.10 to the latest 1.8.25?

On ubuntu 20, I installed tslab (https://tdlib .github.io/td/build.html?language=PHP ), then installed phptdlib (https://github.com/yaroslavche/phptdlib ) and it works successfully. But unsupported Message errors began to occur, which means the tdlib version is outdated and it's time to update it.

I tried to reinstall stdlib 1.8.25 on the same server by deleting the td directory from the previous installation and re-downloaded from GIT and installed, it was installed, but the messages are also unsupportedMessage.

How do I update tdlib correctly and do I need to install phptdlib again?

I'm desperate and I'm asking for help.

**Comment by yaroslavche** [comment]
@kubsite1 Thank you for your patience, I'm a bit late in responding to this issue.
To update the tdlib version, you need to update the git submodules and the version in CMakeLists.txt: here is an example screenshot of a commit with version update changes:
![image](https://github.com/yaroslavche/phptdlib/assets/17838239/8e2147b5-2b03-4eeb-80bd-0b2090eb899e)
To ensure that all submodules are up to date, you can run the following command: `git pull -v --recurse-submodules`
Please note that I no longer support updates for this extension. It is recommended to use FFI in PHP 8, as it provides a more efficient and modern way to interact with C code (like this extension does).

**Comment by kubsite1** [comment]
It is a pity that you are no longer involved in the project, it was a good one. I will try to change the values you specified, if it does not help, I will switch to FFI.

 Thank you for the information!

**Comment by yaroslavche** [comment]
A quick note: don't forget to rebuild tdlib and the extension after updating the submodules. The process is the same as the installation process.

I mentioned in another issue (I'll tag it here if I find it) that you can use a shell script for this, similar to what CI does.

While you can still use the extension, it's important to note that it's designed for PHP 7 and is no longer actively maintained for PHP 8 (including 8.0, which is also EOL). This isn't necessarily an urgent issue, but it's a factor to consider.

By the way, you can find an example using FFI here: https://github.com/yaroslavche/phptdlib-ffi.

**Comment by kubsite1** [comment]
@yaroslavche, I installed the latest tdlib 1.8.27 on a clean Ubuntu 22, downloaded your phptdlib and in cmakelist.txt replaced version 1.8.10 with 1.8.27. 

![2024-04-10_16-26-04](https://github.com/yaroslavche/phptdlib/assets/102043183/7ff080b0-4c01-4044-babe-a8717ddba8a9)

Installed phptdlib and tested:
```
php -i | grep tdlib
php ../php_examples/func.php

```
everything is displayed as 1.8.10 This idea didn't work :(

![2024-04-10_16-27-09](https://github.com/yaroslavche/phptdlib/assets/102043183/80a67e35-3fe3-4e4f-bbc3-67ace8244e98)

**Comment by yaroslavche** [comment]
@kubsite1 try to run this:
`sudo ldconfig`
If this wouldn't help, make sure to firstly remove the old version.
Also, before rebuilding a new version remove `build` directory in extension root. It might contain a cached cmake with an old version.

**Comment by kubsite1** [comment]
@yaroslavche, this command did not output anything, and nothing changed after it 

I don't know much about Linux, but I found how to upgrade and the upgrade was successful )))

There is a /modules/td directory in your phptdlib, I replaced this with the current version of tdlib, replaced the version in phptdlib/CMakeList.txt to the current one and started the installation. 
**Replacing the TD directory in your build is a solution to the upgrade problem.**

Thanks
