### ISSUE TITLE
Error installing 'phttdlib'

### ISSUE THREAD

**Issue by ghost** [yaroslavche/phptdlib#23]
I install all the required dependencies in the project following the indications, but when I try to install [phptdlib](https://github.com/yaroslavche/phptdlib) I get the following error:

```
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindTd.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "Td", but CMake did
  not find one.

  Could not find a package configuration file provided by "Td" (requested
  version 1.3.0) with any of the following names:

    TdConfig.cmake
    td-config.cmake

  Add the installation prefix of "Td" to CMAKE_PREFIX_PATH or set "Td_DIR" to
  a directory containing one of the above files.  If "Td" provides a separate
  development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
```
I have a "MacOS High Sierra v. 10.13.6 with Xcode updated and OpenSSL installed.

**Comment by yaroslavche** [comment]
It's seems like not `phptdlib` issue. As error says: Could not find a package configuration file provided by "Td"
Please, check [this](https://github.com/tdlib/td/issues/305) and [this](https://github.com/tdlib/td/issues/351).

**Comment by ghost** [comment]
Actually the error was not "phttdlib". I thought I had the latest version of "XCode" but it was not like that. When I updated, the problem was solved. Sorry for the inconvenience.
