### ISSUE TITLE
Installation gets stuck on Building one of CXX objects

### ISSUE THREAD

**Issue by aminghaseminia** [yaroslavche/phptdlib#32]
Hello
I've been trying to install this very useful library on my server since morning but there's a problem I can't get it fixed, so it would be appreciated if you give me a hand.
After installation of the required items, when installing the extension itself, in the step when I enter the command 'make' it gets stuck on Installation of one of the objects:

`Building CXX object modules/td/CMakeFiles/tdcore.dir/td/telegram/AnimationsManager.cpp.o`
Almost 1 hour took and then finally I canceled it.
during the installation of this file my CPU usage has been on 100%, used ram is 1.8GB out of 2GB (when not installing the used ram is at most 300MB) and hard drive is reading at the speed of 550MB/s
Thank you.

**Comment by yaroslavche** [comment]
Hi, @aminghaseminia .
I suggest to use CLang for this. As I know - at least 2GB RAM is required. With GCC - 4Gb minimun.
Compilation time depends on tdlib, not this ext.

you must install clang for this and run cmake with next env: `CXX=clang++ CC=clang cmake ...`

**Comment by maxvgi** [comment]
You can also compile the extension at a more powerfull workstation with similar configuration. That could be VPS with more ram/cpu or even your windows/mac desktop with docker.

And copy binaries to your target system after that.

**Comment by aminghaseminia** [comment]
Thank you
Isn't that possible for you to upload the final binaries also?

**Comment by yaroslavche** [comment]
@aminghaseminia final binaries depends at many things. And this must be a lot of binaries. So - no, that's not possible at this moment. Also this extension builds for a few seconds if you have builded tdlib.

**Comment by yaroslavche** [comment]
> TDLib 1.4.0 includes a lot of compilation memory usage optimizations and a new script SplitSource.php, which can be used to split some source code files before building the library to reduce maximum RAM usage per file at the expense of increased build time. In our tests clang 6.0 with libc++ required less than 500 MB of RAM per file and GCC 4.9/6.3 used less than 1 GB of RAM per file.

https://github.com/tdlib/td/issues/67#issuecomment-488386750
