### ISSUE TITLE
Unknown class on calling getLogVerbosityLevel method

### ISSUE THREAD

**Issue by ildarsaitkulov** [yaroslavche/phptdlib#33]
`[ 1][t 0][1564741364.083082199][ClientJson.cpp:89]	Failed to parse [request:{\0042@type\0042:\0042getLogVerbosityLevel\0042}] [Error : 0 : Unknown class]`

Probably need to update tdlib in submodules?

**Comment by yaroslavche** [comment]
Thanks for the reporting, I have reproduced with 1.3.0 (I also have a slightly outdated version). Yes, it seems like need to update. If this does not help and other functions work fine, this problem is more likely related to tdlib/td, rather than this extension.

**Comment by yaroslavche** [comment]
Yes, you completely right. After updating to 1.4.0 it works fine:
```php
$result = $client->execute(json_encode(['@type' => 'getLogVerbosityLevel']));
dd($result);
```
`"{"@type":"logVerbosityLevel","verbosity_level":1}"`
