### ISSUE TITLE
Make calls

### ISSUE THREAD

**Issue by andreybolonin** [yaroslavche/phptdlib#40]
Any chance to make calls via this lib, 
like this https://github.com/grishka/libtgvoip ?

**Comment by yaroslavche** [comment]
> You can receive new calls through updateCall and create new calls using createCall, but calls encrypted data transfer isn't handled by TDLib. You will need to use libtgvoip for that.

https://github.com/tdlib/td/issues/106

For example:
```php
$client->query(json_encode(['@type' => 'createCall', 'user_id' => $userId, 'protocol' => ['udp_p2p' => true, 'udp_reflector' => true, 'min_layer' => 65, 'max_layer' => 77]]));
```
[createCall](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_call.html)

**Comment by andreybolonin** [comment]
@yaroslavche thx
