### ISSUE TITLE
authorizationStateWaitRegistration

### ISSUE THREAD

**Issue by rabbitone** [yaroslavche/phptdlib#41]
Got
 
string(563) "{"@type":"updateAuthorizationState","authorization_state":{"@type":"authorizationStateWaitRegistration","terms_of_service":{"@type":"termsOfService","text":{"@type":"formattedText","text":"By signing up for Telegram, you agree not to:\n\n- Use our service to send spam or scam users.\n- Promote violence on publicly viewable Telegram bots, groups or channels.\n- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n\nWe reserve the right to update these Terms of Service later.","entities":[]},"min_user_age":0,"show_popup":false}}}"

while running client.php

Changes in 1.5.0:
Changed authorization workflow:
Added the state authorizationStateWaitRegistration, which will be received after authorizationStateWaitCode for users who are not registered yet.
Added the method registerUser, which must be used in the authorizationStateWaitRegistration state to finish registration of the user.

**Comment by yaroslavche** [comment]
@rabbitone if I correctly understood, need to send request [registerUser](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1register_user.html).
Sth like this:

```php
td_json_client_send($client, json_encode(['@type' => 'registerUser', 'first_name' => 'John', 'last_name' => 'Doe']));
```

Also maybe need to send [acceptTermsOfService](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1accept_terms_of_service.html), but I can't figure out where in your json example `terms_of_service_id`. May be don't need, IDK.
