### ISSUE TITLE
Error:  Can't parse "@channel_name" as number

### ISSUE THREAD

**Issue by Incher25** [yaroslavche/phptdlib#50]
Hi all,

I try to call 'getChat' method with "\@channel_name" as chat_id (as far as I understand for public channels chat_id is the same as "\@channel_name") but I receive an error: "Failed to parse JSON object as TDLib request: Can't parse "\@channel_name" as number". If I can't use channel name as chat_id, where can I  get channel's numeral id (I didn't find it in channel info section)? 

Thanks for help in advance!

**Comment by Incher25** [comment]
I got chat id via https://telegram.me/getidsbot, than sent getChat with it:
```
$result = $client->query(json_encode(['@type' => 'getChat', 'chat_id' => '-1001173078748']), 10);
```
 but now I receive another error: "code":6,"message":"Chat not found"

**Comment by DerAlSem** [comment]
You should use searchPublicChat method, it will provide you with the id, then you use getChat. If chat not found, it might be private.

**Comment by Incher25** [comment]
When I call searchPublicChat:
```
$result = $client->query(json_encode(['@type' => 'searchPublicChat', 'username' => '@nmtb2']), 10);
```
I get error "code":400,"message":"USERNAME_NOT_OCCUPIED", but channel \@nmtb2 exists and it's public.

**Comment by DerAlSem** [comment]
try nmtb2, without slash and dog

**Comment by Incher25** [comment]
> try nmtb2, without slash and dog

Same result - USERNAME_NOT_OCCUPIED

**Comment by DerAlSem** [comment]
works for me:

`tdsend('searchPublicChat', ['username' => 'nmtb2']);`

partial output of update (tdsend for your reference below): 

> [@type] => updateSupergroupFullInfo                                [15/1887]
>     [supergroup_id] => 1173078748
>     [supergroup_full_info] => Array
>         (
>             [@type] => supergroupFullInfo
>             [description] => Маша, книги-музыка-путешествия-кино.
> 
> В рекламе не нуждаюсь, никого рекламировать не буду. Обратная связь для прочего
> @revol_junk
> 
> Основной канал на YT https://www.youtube.com/c/NeverMindTheBooks
>             [member_count] => 1010
>             [administrator_count] => 0

```
function tdsend($type, $parameters = [])
{
    global $client;
    $query = [
        '@type' => $type,
    ];
    foreach ($parameters as $parameter => $value) {
        $query[$parameter] = $value;
    }
    //var_dump($query);
    td_json_client_send($client, json_encode($query));
}
```

**Comment by Incher25** [comment]
@DerAlSem thanks for your reply! As far as I understand JsonClient handles responses receiving and If I'm going to use td_json_client_send() instead of JsonClient methods I need to write my own implementation of  responses receiving, but I don't know how to do it properly. Could you share any example of it?
I tried to implement it according to this example https://github.com/yaroslavche/phptdlib#example but I always receive  '{"\@type":"authorizationStateWaitTdlibParameters"}' no matter what request I send.

**Comment by DerAlSem** [comment]
You're on the right way, but seems you didn't read till the end. Everything is explained in the example. See:

Example. Simple workflow:

_1. create a client_
**you're here**
_2. setTdlibParameters
3. if need, setDatabaseEncryptionKey
4. if getAuthorizationState returns authorizationStateWaitPhoneNumber, then setAuthenticationPhoneNumber
5. if getAuthorizationState returns authorizationStateWaitCode, then checkAuthenticationCode
6. if getAuthorizationState returns authorizationStateReady, then you are allowed to do what you want with tdlib/td (Function class reference)._

So simply send smth like:

                              ```
  $tdlibparams = [
                                    'use_test_dc_' => true,
                                    'database_directory' => "$pwd/db",
                                    'files_directory' => "$pwd/files",
                                    'use_file_database' => true,
                                    'use_chat_info_database' => true,
                                    'use_message_database' => true,
                                    'use_secret_chats' => false,
                                    'api_id' => $api_id,
                                    'api_hash' => $api_hash,
                                    'system_language_code' => 'ru',
                                    'device_model' => php_uname('s'),
                                    'system_version' => php_uname('v'),
                                    'application_version' => '0.0.1',
                                    'enable_storage_optimizer' => true,
                                    'ignore_file_names' => false
                                ];
                                tdsend('setTdlibParameters', [
                                    'parameters' => $tdlibparams
                                ]);
```

**Comment by yaroslavche** [comment]
> As far as I understand JsonClient handles responses receiving and If I'm going to use td_json_client_send() instead of JsonClient methods I need to write my own implementation of responses receiving, but I don't know how to do it properly.

`\TDLib\JsonClient` is a extended class from `\TDLib\BaseJsonClient`. `BaseJsonClient` is used when you call `td_json_client_send`: [td_json_client_func_send](https://github.com/yaroslavche/phptdlib/blob/master/include/td_json_client_func.cpp#L30). And also same object will be used, when you call `$client->send(...)` [JsonClient::send](https://github.com/yaroslavche/phptdlib/blob/master/include/TDLib/JsonClient.hpp#L30). And behavior like this in whole extension: we have `td_json_client_...` which was used in other classes with helpful wrappers and sugar.
So, if simple, following is equivalent:
```php
$client = new \TDLib\JsonClient();

td_json_client_send($client, "...");
$client->send("...");
```

I would suggest use a JsonClient, since it contains a helpful methods like `query` and `getReceivedResponses`. `query` is good method, when you need receive response to async `td_json_client_send`. Simple pseudocode:
```
function query(string $json)
{
    $arguments = json_decode($json, true); // parse json request into array
    $extra = $arguments['@extra'] = mt_rand(); // add to array @extra key
    td_json_client_send(json_encode($arguments)); // send request
    while (true || $timeout) {
        $response = td_json_client_receive(); // receive a response. This can be response to other request
        if ($response->extra === $extra) { // check if extra equals. If yes - then we waiting it
            return $response;
        }
        // otherwise need to store received in internal array
        collectReceivedResponses(); // which can be accesses with getReceivedResponses()
    }
}
```

Also please check [this](https://core.telegram.org/tdlib/getting-started), and [this](https://yaroslavche.github.io/phptdlib/documentation.html). Hope this helps =)
And yes, you must configure the client before requesting it. You should send these requests: `setTdlibParameters`, `setDatabaseEncryptionKey`, `setAuthenticationPhoneNumber`. `\TDLib\JsonClient` have a wrappers for these requests (same name, see in readme example). In fact, this is a `\TDLib\JsonClient::query`, which really is a `td_json_client_send` and `td_json_client_receive` =)
So, following is also equivalent:
```php
    $tdlibParams = new \TDApi\TDLibParameters();
    $tdlibParams
        ->setParameter(\TDApi\TDLibParameters::USE_TEST_DC, true)
        // ...
        ;
    $result = $client->setTdlibParameters($tdlibParams);
```
and
```
    $tdlibParams = [
        'use_test_dc_' => true,
        // ...
    ];
    $client->send(json_encode(['@type' => 'setTdlibParameteres', 'parameters' => $tdlibParams]))
    $result = $client->receive(); // some methods returns couple responses to request, so not a fact that response will be to a request (`send`) above.
```
Two methods above in fact will use `td_json_client_send($client, json_encode(['@type' => 'setTdlibParameteres', 'parameters' => $tdlibParams]))`
Difference is that `JsonClient` gives you capability to write less code and without it you should handle responses and react to them in way you want.

**Comment by Incher25** [comment]
@DerAlSem , @yaroslavche thanks for help!  I would like to use JsonClient too:) But when I  use it to get chat_id or to get channel info by this chat_id I receive errors like the channel doesn't exist (but it does):
 ```
// This code returns 'error "code":400,"message":"USERNAME_NOT_OCCUPIED"':
$result = $client->query(json_encode(['@type' => 'searchPublicChat', 'username' => 'nmtb2']), 10);

// And this code returns 'error: "code":6,"message":"Chat not found"':
$result = $client->query(json_encode(['@type' => 'getChat', 'chat_id' => '-1001173078748']), 10);
```
So I thought If I will use td_json_client_... functions instead, it would work.

**Comment by Incher25** [comment]
Well, using `td_json_client_...` functions makes no sence - I still receive '"error","code":400,"message":"USERNAME_NOT_OCCUPIED"'.

My WebSocketServer code (I used @yaroslavche's [tdlib-bundle](https://github.com/yaroslavche/tdlib-bundle) as an example): 
```
public function __construct(OutputInterface $output, array $tdlibParameters, array $clientConfig)
    {
        $this->ready = true;
        $this->output = $output;
        try {
            $this->client = td_json_client_create();
            $setTdlibParametersResponse = $this->query($this->client, json_encode([
                '@type' => 'setTdlibParameters',
                'parameters' => $tdlibParameters
            ]));

            $checkDatabaseEncryptionKeyResponse = $this->query($this->client, json_encode([
                '@type' => 'checkDatabaseEncryptionKey',
                'encryption_key' => $clientConfig['encryption_key'] ?? ''
            ]));
        } catch (Exception $e) {
            $this->ready = false;
            $this->output->writeln($e->getMessage());
        }
    }

...
public function onMessage(ConnectionInterface $from, $message)
    {

        $this->output->writeln(sprintf('Request: %s', $message));
        if ($this->ready) {
            $response = $this->query($this->client, $message);
            $this->output->writeln(sprintf('Response: %s', $response));
            $from->send($response);
        } else {
            $from->send(json_encode(['@type' => 'error']));
        }
    }

public function query($client, $json, $timeout = 10)
    {
        $start = time();
        $arguments = json_decode($json, true); // parse json request into array
        $extra = $arguments['@extra'] = mt_rand(); // add to array @extra key
        td_json_client_send($client, json_encode($arguments)); // send request
        //while (true || ((time() - $start) < $timeout)) {
        while (true || $timeout) {
            $response = td_json_client_receive($client, $timeout); // receive a response. This can be response to other request
            //var_dump($response['@extra']);
            $responseArray = json_decode($response, true);
            if ($responseArray['@extra'] === $extra) { // check if extra equals. If yes - then we waiting it
                return $response;
            }
            // otherwise need to store received in internal array
            $this->collectReceivedResponses(); // which can be accesses with getReceivedResponses()
        }
    }

```
In my WebSocketClient I make following requests:
```
\Ratchet\Client\connect('ws://127.0.0.1:12345')->then(function($conn) {
            $conn->on('message', function($msg) use ($conn) {
                echo "Received: {$msg}\n";
                //$conn->close();
            });

            $conn->send(json_encode(['@type' => 'getAuthorizationState']));
            $conn->send(json_encode(['@type' => 'searchPublicChat', 'username' => 'nmtb2']));

        }, function ($e) {
            echo "Could not connect: {$e->getMessage()}\n";
        });
```

and here is WebSocketClient's output:
```
Received: {"@type":"authorizationStateReady","@extra":1545898827}
Received: {"@type":"error","code":400,"message":"USERNAME_NOT_OCCUPIED","@extra":2027430678}
```

**Comment by yaroslavche** [comment]
Please copy all code except api credentials and phone. And all requests and responses. You can use pastebin for this.
It's seems to me impossible. You something doing wrong. Why you copy a pseudocode from my prev message? This is obviously is not a needed code, just an example. Also query method exists inside `JsonClient`, no need to write it again. 
Also you SHOULD understand one thing. If you can send and receive ANY data from tdlib, then you CAN assume, that phptdlib is WORKING fine. Just use API correctly. It's not related to phptdlib

**Comment by yaroslavche** [comment]
also you have an examples on code, what you have mentioned:
```php
            $setTdlibParametersResponse = $this->query($this->client, json_encode([
                '@type' => 'setTdlibParameters',
                'parameters' => $tdlibParameters
            ]));
```
Should be
```
            $setTdlibParametersResponse = $this->jsonClient->query(json_encode([
                '@type' => 'setTdlibParameters',
                'parameters' => $tdlibParameters
            ]));
```
Because we already have a client.
this almost similar thing to following:
```
td_json_client_send($this->client, json);
while (true) {
    $setTdlibParametersResponse = td_json_client_receive();
}
```
It waits response in `while`. But not a fact, that response will be `{"@type":"Ok"}`. Even if all things are ok, you firstly can receive response with some options, that you should handle, if want.

In [tdlib-bundle](https://github.com/yaroslavche/tdlib-bundle) just run as in documentation says. And then, when was authorized, send next request:
```json
{"@type":"searchPublicChat","username":"nmtb2"}
```
P.S. Feel free to write me in Telegram (yaroslavche). I will try to explain better in russian (since I can suppose that you a russian-speaker)

AFAIK, @DerAlSem has a similar issue and perfectly handle it. Help wanted =)

**Comment by yaroslavche** [comment]
@Incher25 I suppose, #53  here a similar (almost) issue in russian =)

**Comment by DerAlSem** [comment]
First of all - have you tried simply send some message?

**Comment by Incher25** [comment]
@yaroslavche Thanks a lot! I've solved it, it was my silly mistake - I forgot to set TDApi\TDLibParameters::USE_TEST_DC to false instead of true.
Thanks for link to #53, it was helpfull :)
