### ISSUE TITLE
Перестали приходить коды для login после вызова setAuthenticationPhoneNumber 

### ISSUE THREAD

**Issue by merlinkory** [yaroslavche/phptdlib#55]
Добрый день! 
Неделю назад столкнулись с проблемой,  что  в нашем приложение после вызова setAuthenticationPhoneNumber  на указанный номер перестали приходить коды для входа, хотя судя по логам TDlib код был успешно отправлен и статус в нашем приложение сменился на authorizationStateWaitCode. 

Позже выяснилось что код приходит только в 5 % случаях (примерно). т.е. на например на номер ххх сегодня код не приходит (естественно после у нас есть около 5 попыток в сутки) а через пару дней приходит, но только один или два раза а потом перестает приходить (до выхода лимита на отправку по этому номеру). 

Закономерность совершенно не понятна, тестировали с множеством разных телефонных номеров как и в РФ так и за пределами. В начали грешили на сервер и API ключи, но  когда развернули новый сервер с полностью новыми API ключами (запустили только кусок кода с отправкой auth code ) тоже самое - точнее с новыми вообще не разу код не пришел, хотя судя же по логам код отправляется.  TDLIB и PHP TDLIB  у  нас последней версии.

Может у вас есть какие то идеи почему это может происходить? А то у нас уже варианты кончились да и поддержка tdlib не может помочь. 
Вот если что ветка issue на tdlib репозитории  https://github.com/tdlib/td/issues/925

**Comment by yaroslavche** [comment]
Ну во первых я могу посоветовать попробовать собрать с более ранней версией тдлиб (1.5, например), проверить, работает ли, или наблюдается та же проблема. Если та же, то скорее всего это не будет зависить ни от расширения, ни от версии тдлиб и ответа надо ждать от саппорта телеграма.

В `CMakeLists.txt` вместо `1.6.1` укажите конкретную, и для этой версии установите необходимую по коммиту или тегу (релизу).

**Comment by merlinkory** [comment]
Уже пробовали, на других версиях тоже самое. причем на другом совершенно сервере с другими API ключами, так же в один момент перестали коды приходить. причем у авторизованных сессий - все продолжает работать отлично.

А не подскажите в какой именно саппорт в телеграм можно обратиться ?

**Comment by yaroslavche** [comment]
Довольно странно.
Могу лишь сказать, что в таком случае очевидно это не зависит от расширения, раз работает так же. Кстати, я вчера заметил, что мой десктопный клиент телеграма тоже подлагивает странным образом.

Обращаться [сюда](https://telegram.org/support), но они могут не ответить =) я два раза писал за последние 2 года, ни разу не получил ответа =)
Рад бы помочь, но не знаю чем и как.

**Comment by yaroslavche** [comment]
~Еще, возможно, попробуйте очистить кеш самой базы, которая хранится по путях, что Вы указываете в TdlibParameteres. Но сначала обязательно сделайте бекап.~
Хотя на другом серевере она была чистая, и это не помагает.

**Comment by merlinkory** [comment]
Буду пробовать писать в саппорт... Все другое перепробовал
Скажите, а у вас нормально setAuthenticationPhoneNumber работает, всегда приходит код без перебоев ?

**Comment by yaroslavche** [comment]
Лично я не пользуюсь расширением =) Оно у меня даже не установлено. Сейчас, тдлиб билдится, я попробую и потом отвечу, получил ли я код.

**Comment by yaroslavche** [comment]
> Скажите, а у вас нормально setAuthenticationPhoneNumber работает, всегда приходит код без перебоев ?

Проверил, если у меня `\TDApi\TDLibParameters::USE_TEST_DC = true`, тогда исправно приходит СМС, если `false` - код в десктопном клиенте. У меня сработало с первого раза.
Видимо у Вас что-то или с номером, или с айпи. Так как Вы пробовали другие номера и сервер, может стоит попробовать впн/[прокси](https://github.com/yaroslavche/phptdlib/issues/26#issuecomment-458006632)? Или попробуйте воспроизвести на локальной машине.

**Comment by DerAlSem** [comment]
Для НЕ тестового DC нужно кучу всего прописывать, иначе оно работать не будет.

Тестовый как раз и нужен для тестирования. Возможно имеет смысл указать, что "не меняйте на false, если не понимаете, что это и зачем". :)

**Comment by merlinkory** [comment]
Да с USE_TEST_DC = true код в СМС приходить оке. но  если false то в  десктопное  или в приложение на телефоне не приходит (точнее так же  приходит непонятно с  какой попытки, и в разный день на разные телефонные номера. В один день не приходит на один в другой на другой...  уменя для теста уже 10 разных телефонов). И опять по логам все оке...

Причем все ранее залогиненые сессии в моем приложение продолжают работать без каких либо перебоев...  Я думаю это какое то новое  нововеденное ограничение телеграмма появилось... но support от них молчит :(

Грешил на API_ID но поменял на новые -  тоже самое...  Попробую сбилдить локально и попробовать . сейчас все работает в AMAZON (frankfurt, oregon andn Tokyo)

**Comment by merlinkory** [comment]
На локальной рабочей машине кстати все запустилось и коды отправляються без проблем!!!!  Не работает именно из Амазона (причем пробовал в амазоне в разных локациях и на разных учетных  записях)...

Вот такая вот странность

**Comment by yaroslavche** [comment]
> На локальной рабочей машине кстати все запустилось и коды отправляються без проблем!!!! Не работает именно из Амазона (причем пробовал в амазоне в разных локациях и на разных учетных записях)...

Видимо, проблема таки с амазоном. Думаю, можно еще их саппорт спросить, почему на локальной машине работает, а на амазоне нет =) Возможно упирается в какие-то ограничения, но не должно.
