### ISSUE TITLE
How I must start main script on my web server?

### ISSUE THREAD

**Issue by HellFinger-s** [yaroslavche/phptdlib#58]
How can I run the main script on the server? Should I call it from the terminal, or is there another way

**Comment by yaroslavche** [comment]
As you want. `phptdlib` is extension and should work in any script (if enabled).

**Comment by HellFinger-s** [comment]
I mean how i can start my script? Or it will be enable automatically if some update will come?

**Comment by HellFinger-s** [comment]
Or i should call script from terminal and forget him

**Comment by yaroslavche** [comment]
>  will be enable automatically

nothing will enable automatically. You should create and configure client and keep it working (or init on each run). How you achieve that not matter. It's up to you to decide, there is no "recommendations" how to do this.

Look at this as PHP with extension (which allow to create client). PHP have many ways to create an async app. Extension don't do this, you should do within PHP.

**Comment by HellFinger-s** [comment]
Understood, thanks
