### ISSUE TITLE
Как избавиться от ошибки "Timeout waiting for response"?

### ISSUE THREAD

**Issue by trueSiberian** [yaroslavche/phptdlib#60]
Как избавиться от ошибки "Timeout waiting for response"?

Сначала она была редкой, теперь в 8/10 случаев я не могу получить данные

 $this->client->setDefaultTimeout(60); - уставновил

`try {
            TDApi\LogConfiguration::setLogVerbosityLevel(\TDApi\LogConfiguration::LVL_ERROR);

            $this->client = new TDLib\JsonClient();
            // $this->client->getAuthorizationState();

            $tdlibParams = new TDApi\TDLibParameters();
            $tdlibParams
                ->setParameter(TDApi\TDLibParameters::USE_TEST_DC, false)
                ->setParameter(TDApi\TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
                ->setParameter(TDApi\TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
                ->setParameter(TDApi\TDLibParameters::USE_FILE_DATABASE, false)
                ->setParameter(TDApi\TDLibParameters::USE_CHAT_INFO_DATABASE, false)
                ->setParameter(TDApi\TDLibParameters::USE_MESSAGE_DATABASE, false)
                ->setParameter(TDApi\TDLibParameters::USE_SECRET_CHATS, false)
                ->setParameter(TDApi\TDLibParameters::API_ID, $this->api_id)
                ->setParameter(TDApi\TDLibParameters::API_HASH, $this->api_hash)
                ->setParameter(TDApi\TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
                ->setParameter(TDApi\TDLibParameters::DEVICE_MODEL, php_uname('s'))
                ->setParameter(TDApi\TDLibParameters::SYSTEM_VERSION, php_uname('v'))
                ->setParameter(TDApi\TDLibParameters::APPLICATION_VERSION, '0.0.10')
                ->setParameter(TDApi\TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
                ->setParameter(TDApi\TDLibParameters::IGNORE_FILE_NAMES, false);
            $this->client->setTdlibParameters($tdlibParams);
            $this->client->setDefaultTimeout(30);
            $this->client->setDatabaseEncryptionKey(); // checkDatabaseEncryptionKey(key) or DESTROY
        } catch (\Exception $exception) {
            echo sprintf('something goes wrong: %s', $exception->getMessage());
        }`

**Comment by yaroslavche** [comment]
Во первых, этот весь код падает в таймаут? - не очень верится =) Описывайте проблему немного точнее пожалуйста. На какой строке, в каком методе. Вот [тут](https://github.com/yaroslavche/phptdlib/issues/26) была похожая проблема. Так же это может [случаться](https://github.com/tdlib/td/issues/730).

Во вторых, не нужно устанавливать 60 секунд, потому что увеличение время ожидания не увеличивает шансы ответа. В целом 5-10 секунд вполне должно быть достаточно. `setDefaultTimeout` это вспомогательный метод, попробуйте без него: у методов `receive` и `query` есть второй аргумент `timeout`.
