### ISSUE TITLE
setProfilePhoto

### ISSUE THREAD

**Issue by TadavomnisT** [yaroslavche/phptdlib#66]
Hi, and Thank you for this incredible library!
I've built it, and compiled it successfully, and also logged in .
Everything is fine!
I'm trying to upload a profile photo for my telegram account. but here is the result:

`something goes wrong: Error parsing json`

I know that I am doing something wrong about inputPhoto but although reading the whole document , I have no idea how to implement the image that can be parsed by Json class.
Here is the part of code:  

```
    $image=imagecreatefrompng("candle.png");
    $result = $client->query(json_encode(['@type' => 'setProfilePhoto', 'photo' => $image]), 10);
    var_dump($result);
```

and I wish if you could show me an example of setProfilePhoto, just like the example of sendMessage in your documentation.

Thank you for your time.

**Comment by yaroslavche** [comment]
Hi.
In general, you should pass `photo` as `inputFileGenerated` or `inputFileLocal` ([inputFile](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_input_file.html), inputFileId and inputFileRemote may still be unsupported). Not as php image resource.
I can't check if this would work, but try this ([with local file path](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_local.html)):
```
    $imagePath = 'candle.png';
    $result = $client->query(json_encode(['@type' => 'setProfilePhoto', 'photo' => ['path' => $imagePath]]), 10);
    var_dump($result);
```

**Comment by TadavomnisT** [comment]
Thank You for this quick answer, and your great support.
Thanks to you, here is the correct code(we have to specify the type of InputPhoto):

```
$imagePath = dirname(__FILE__).'/candle.png';//Works for PHP >= 4.0.2
    // $imagePath = realpath('candle.png');
    $result = $client->query(json_encode(['@type' => 'setProfilePhoto', 'photo' => ['@type' => 'inputFileLocal','path' => $imagePath]]), 100);
    var_dump($result);
```
and I mentioned 2 ways to get local path.

and for those who have stored image in resource, first they gotta save image in file, then pass the real path of file.

BTW this shouldn't be marked as issue, it's my lack of knowledge :*
again, Thanks for the help.
