### ISSUE TITLE
 Failed to find PHP-CPP

### ISSUE THREAD

**Issue by sallsabil** [yaroslavche/phptdlib#7]
Hello
Thanks for your project
I have installed PHP-CPP

but I recieve this error:
root@mygr:~/projects/phptdlib/build# cmake ..
CMake Error at CMakeLists.txt:15 (message):
  Failed to find PHP-CPP

-- Configuring incomplete, errors occurred!
See also "/root/projects/phptdlib/build/CMakeFiles/CMakeOutput.log".

**Comment by sallsabil** [comment]
fixed
CMakeLists.txt:15:
`find_library(PHPCPP NAMES phpcpp php-cpp)`

**Comment by sallsabil** [comment]
another error:

/usr/include/phpcpp/namespace.h:249:16: note: Php::Namespace& Php::Namespace::add(const Php::Namespace&)
     Namespace &add(const Namespace &ns)
                ^
/usr/include/phpcpp/namespace.h:249:16: note:   candidate expects 1 argument, 3 provided
CMakeFiles/tdlib.dir/build.make:62: recipe for target 'CMakeFiles/tdlib.dir/tdlib.cpp.o' failed
make[2]: *** [CMakeFiles/tdlib.dir/tdlib.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tdlib.dir/all' failed
make[1]: *** [CMakeFiles/tdlib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yaroslavche** [comment]
It seems that this is not the whole output of errors in the console. Please copy everything from
```bash
root@mygr:~/projects/phptdlib/build# make
```
Are you sure that you have installed PHP-CPP 2.0.0? You can check this with a command:
```bash
cat /usr/include/phpcpp/version.h
```
in my case PHPCPP_API_VERSION  20150126

The last commit from the master?
What OS, c++ compiler?

I just tried:
```
yaroslav@localhost:~/projects> git clone https://github.com/yaroslavche/phptdlib
yaroslav@localhost:~/projects>  cd phptdlib
yaroslav@localhost:~/projects/phptdlib> mkdir build && cd build
yaroslav@localhost:~/projects/phptdlib/build> cmake ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yaroslav/projects/phptdlib/build
yaroslav@localhost:~/projects/phptdlib/build> make
Scanning dependencies of target tdlib
[ 25%] Building CXX object CMakeFiles/tdlib.dir/tdlib.cpp.o
[ 50%] Building CXX object CMakeFiles/tdlib.dir/include/TDLib/JsonClient.cpp.o
[ 75%] Building CXX object CMakeFiles/tdlib.dir/include/TDApi/TDLibParameters.cpp.o
[100%] Linking CXX shared library tdlib.so
[sudo] password for root: 
[100%] Built target tdlib
```

Everything seems to be working. I would like to help, but I can't understand the problem.
And thanks for the interest =)

P.S. And so far I will delete the library check in CMakeLists.txt in next commit. I seriously don't know how to correctly check the version of the installed PHP-CPP.

**Comment by sallsabil** [comment]
by the way

> find_library(PHPCPP NAMES phpcpp php-cpp)

was wrong.

Are you sure that you have installed PHP-CPP 2.0.0?
yes
PHPCPP_API_VERSION  20150126

![image](https://user-images.githubusercontent.com/19548273/37014337-2c79382a-2115-11e8-9432-799a3a4347d5.png)

**Comment by yaroslavche** [comment]
Like the error message says, you need to compile with the -std=c++11 or -std=gnu++11 compiler options. Have you tried doing that? 
Which compiler do you use?
I have gcc version 7.3.0 (`g++ -v`)

Try to add
`USE_CXX11()`
or
`SET (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")`
in CMakeLists.txt

**Comment by sallsabil** [comment]
Good
Thank you
Worked:
`SET (CMAKE_CXX_FLAGS "-std=c++14 ${CMAKE_CXX_FLAGS}")`

I thought `-std=c++14` is better.

**Comment by svddevelop** [comment]
Hallo @yaroslavche 
I have same problem.

![Unbenannt1](https://github.com/yaroslavche/phptdlib/assets/12089184/a9c88a5b-1ca9-4b93-bc01-aba3b4874a33)

hire is my CMakeList.txt
`phptdlib/build# cat ../CMakeLists.txt
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)

SET (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")

set(EXT_NAME tdlib)
set(EXT_VERSION 0.0.10)
project(${EXT_NAME} VERSION ${EXT_VERSION} LANGUAGES CXX)



set(PHP_CONFIG_FILENAME php-config)


#To compile for another PHP version choose the correct php-config, for example
#   set(PHP_CONFIG_FILENAME php-config7.2)

#If you want to preinstalled libraries (not to compile them every time), set the following flags:
#   set(USE_SHARED_TD ON)
#   set(USE_SHARED_JSON ON)
#   set(USE_SHARED_PHPCPP ON)

#By default tests are compiled in debug build and not compiled in release. If you want to
#change this begaviour manualy, you can set the following constant to ON or OFF:
#   set(TDLIB_BUILD_TESTS ON)


#PHP-CPP has an error in CMakeLists.txt. So, currently we can use it only as a shared library:
set(USE_SHARED_PHPCPP ON)






set(CMAKE_CXX_STANDARD 11)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

if(NOT WIN32)
    string(ASCII 27 Esc)
    set(ColourReset "${Esc}[m")
    set(ColourBold  "${Esc}[1m")
    set(Red         "${Esc}[31m")
    set(Green       "${Esc}[32m")
    set(Yellow      "${Esc}[33m")
    set(Blue        "${Esc}[34m")
    set(Magenta     "${Esc}[35m")
    set(Cyan        "${Esc}[36m")
    set(White       "${Esc}[37m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;37m")
endif()


###################
#Determining PHP properties
###################

find_program(PHP_CONFIG NAMES ${PHP_CONFIG_FILENAME})
if(NOT PHP_CONFIG)
    message(SEND_ERROR "Failed to find ${PHP_CONFIG_FILENAME}")
    return()
endif()

execute_process(
        COMMAND ${PHP_CONFIG} --php-binary
        OUTPUT_VARIABLE PHP_BINARY
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
        COMMAND ${PHP_CONFIG} --include-dir
        OUTPUT_VARIABLE PHP_INCLUDE_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
        COMMAND ${PHP_CONFIG} --configure-options
        COMMAND sed -ne "s/^.*--with-config-file-scan-dir=\\([^ ]*\\).*/\\1/p"
        OUTPUT_VARIABLE PHP_CONFIG_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
        COMMAND ${PHP_CONFIG} --extension-dir
        OUTPUT_VARIABLE PHP_EXTENSIONS_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
        COMMAND ${PHP_CONFIG} --vernum
        OUTPUT_VARIABLE PHP_VERSION_NUMBER
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
        COMMAND ${PHP_BINARY} -r "echo PHP_INT_SIZE*8;"
        OUTPUT_VARIABLE PHP_BIT_ARCHITECTURE
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(PHP_VERSION_NUMBER LESS 70000)
    message(SEND_ERROR "PHP-CPP works only with PHP ^7.0. For older PHP versions, use the PHP-CPP-LEGACY instead.")
    return()
endif()



###################
#Compiling dependencies
###################

if(USE_SHARED_TD)
    find_package(Td 1.8.10 REQUIRED)
    if(NOT Td_FOUND)
        message(SEND_ERROR "Failed to find Td")
        return()
    endif()
    set(TD_LINK
            Td::TdJson
            Td::TdStatic
            )
else()
    add_subdirectory(modules/td EXCLUDE_FROM_ALL)
    set(TD_LINK
            Td::TdJsonStatic
            Td::TdStatic
            )
endif()

if(USE_SHARED_PHPCPP)
    find_library(PHPCPP phpcpp)
    if(NOT PHPCPP)
        message(SEND_ERROR "Failed to find PHP-CPP")
        return()
    endif()
else()
    # PHP-CPP now has incorrect CMakeLists.txt, so it could not be compiled via add_subdirectory.
    # Waiting for fixes in PR 399 to be applied. Use USE_SHARED_PHPCPP instead of this.
    message(SEND_ERROR "Currently PHP-CPP can be used only as a shared library. Use -DUSE_SHARED_PHPCPP option")

    set(PHPCPP_PHP_PATH "${PHP_INCLUDE_DIR}" CACHE STRING "")
    if("${PHP_BIT_ARCHITECTURE}" STREQUAL "64")
        set(PHPCPP_ARCH "x86_64" CACHE STRING "")
    else()
        set(PHPCPP_ARCH "x86" CACHE STRING "")
    endif()
    include_directories(modules/PHP-CPP modules/PHP-CPP/include)
    add_subdirectory(modules/PHP-CPP EXCLUDE_FROM_ALL)
endif()

if(USE_SHARED_JSON)
    find_file(NLOHMANN_JSON_INCLUDE_FILE nlohmann/json.hpp)
    if(NOT NLOHMANN_JSON_INCLUDE_FILE)
        message(SEND_ERROR "Failed to find nlohmann_json")
    endif()
    set(NLOHMANN_JSON_LINK, "")
else()
    set(JSON_BuildTests OFF CACHE INTERNAL "")
    include_directories(modules/json/include)
    add_subdirectory(modules/json EXCLUDE_FROM_ALL)
    set(NLOHMANN_JSON_LINK, "nlohmann_json::nlohmann_json")
endif()


###################
#Compiling phptdlib
###################

set(SOURCE_FILES
        tdlib.cpp
        include/TDLib/BaseJsonClient.cpp
        include/TDLib/JsonClient.cpp
        include/TDApi/TDLibParameters.cpp
        include/TDApi/TDLibLogConfiguration.cpp
        include/td_json_client_func.cpp
        include/common.cpp
        )
set(EXT_INI_FILE ${EXT_NAME}.ini)
set(CMAKE_SHARED_LIBRARY_PREFIX "")

if(APPLE)
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -undefined dynamic_lookup")
endif()

add_library(${EXT_NAME} SHARED ${SOURCE_FILES})

target_link_libraries(${EXT_NAME}
        PRIVATE
            ${TD_LINK}
            ${NLOHMANN_JSON_LINK}
        PUBLIC
            phpcpp
        )


###################
#Generating configuration file
###################
set(EXT_LIBRARY_FILENAME "${CMAKE_SHARED_LIBRARY_PREFIX}${EXT_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}")
set(EXT_INI_CONTENTS "extension=${EXT_LIBRARY_FILENAME}")
file(WRITE ${PROJECT_BINARY_DIR}/${EXT_INI_FILE} "${EXT_INI_CONTENTS}")

###################
#Extension installation instructions
###################

install(TARGETS ${EXT_NAME} DESTINATION ${PHP_EXTENSIONS_DIR})

if("${PHP_CONFIG_DIR}" STREQUAL "")
    install(CODE "MESSAGE(\"\nThe extension is installed to ${PHP_EXTENSIONS_DIR}/${EXT_LIBRARY_FILENAME}

Now you have to ${Red}add the following line${ColourReset} at the end of your php.ini
${BoldRed}manually${ColourReset} ${Red}to be able to use the extension${ColourReset}:
    ${EXT_INI_CONTENTS}\")")
else()
    install(FILES ${PROJECT_BINARY_DIR}/${EXT_INI_FILE} DESTINATION ${PHP_CONFIG_DIR})
endif()

if(NOT DEFINED TDLIB_BUILD_TESTS)
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        set(TDLIB_BUILD_TESTS ON)
    else()
        set(TDLIB_BUILD_TESTS OFF)
    endif()
endif()

if(TDLIB_BUILD_TESTS)
    set(INTERFACE_POSITION_INDEPENDENT_CODE ON)

    file(GLOB TEST_SOURCES tests/src/*.cpp)

    add_executable(tester
            ${SOURCE_FILES}
            ${TEST_SOURCES}
            )

    target_link_libraries(tester
            ${TD_LINK}
            ${NLOHMANN_JSON_LINK}
            phpcpp
            php7
            )
endif()`

and CMakeError.Log:

`phptdlib/build# cat CMakeFiles/CMakeError.log
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WCXX14_COMPAT_PEDANTIC failed with the following output:
Change Dir: /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_ecb5b/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_ecb5b.dir/build.make CMakeFiles/cmTC_ecb5b.dir/build
gmake[1]: Entering directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_ecb5b.dir/src.cxx.o
/usr/bin/c++ -DHAVE_CXX_FLAG_WCXX14_COMPAT_PEDANTIC  -std=c++11  -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wimplicit-fallthrough=2 -Wpointer-arith -Wcast-qual -Wsign-compare -Wduplicated-branches -Wduplicated-cond -Walloc-zero -Wlogical-op -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wc++14-compat-pedantic -fPIE   -Wc++14-compat-pedantic -o CMakeFiles/cmTC_ecb5b.dir/src.cxx.o -c /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command-line option '-Wc++14-compat-pedantic'
c++: error: unrecognized command-line option '-Wc++14-compat-pedantic'
gmake[1]: *** [CMakeFiles/cmTC_ecb5b.dir/build.make:78: CMakeFiles/cmTC_ecb5b.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_ecb5b/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WUNUSED_COMMAND_LINE_ARGUMENT failed with the following output:
Change Dir: /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_39582/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_39582.dir/build.make CMakeFiles/cmTC_39582.dir/build
gmake[1]: Entering directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_39582.dir/src.cxx.o
/usr/bin/c++ -DHAVE_CXX_FLAG_WUNUSED_COMMAND_LINE_ARGUMENT  -std=c++11  -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wimplicit-fallthrough=2 -Wpointer-arith -Wcast-qual -Wsign-compare -Wduplicated-branches -Wduplicated-cond -Walloc-zero -Wlogical-op -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wdeprecated -Wno-unused-command-line-argument -fPIE   -Wunused-command-line-argument -o CMakeFiles/cmTC_39582.dir/src.cxx.o -c /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command-line option '-Wunused-command-line-argument'; did you mean '-Wunused-dummy-argument'?
gmake[1]: *** [CMakeFiles/cmTC_39582.dir/build.make:78: CMakeFiles/cmTC_39582.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_39582/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_QUNUSED_ARGUMENTS failed with the following output:
Change Dir: /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_fa48c/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_fa48c.dir/build.make CMakeFiles/cmTC_fa48c.dir/build
gmake[1]: Entering directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_fa48c.dir/src.cxx.o
/usr/bin/c++ -DHAVE_CXX_FLAG_QUNUSED_ARGUMENTS  -std=c++11  -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wimplicit-fallthrough=2 -Wpointer-arith -Wcast-qual -Wsign-compare -Wduplicated-branches -Wduplicated-cond -Walloc-zero -Wlogical-op -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wdeprecated -Qunused-arguments -fPIE   -Qunused-arguments -o CMakeFiles/cmTC_fa48c.dir/src.cxx.o -c /home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command-line option '-Qunused-arguments'
c++: error: unrecognized command-line option '-Qunused-arguments'
gmake[1]: *** [CMakeFiles/cmTC_fa48c.dir/build.make:78: CMakeFiles/cmTC_fa48c.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/home/ubuntu/phptdlib/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_fa48c/fast] Error 2


Source file was:
int main() { return 0; }`
-------------------------------------


**What I did incorrect?**

**Comment by yaroslavche** [comment]
@svddevelop error (on screenshot) says, that you haven't installed PHP-CPP. Please try to install it first (or check path if already installed). Errors in `CMakeFiles/CMakeError.log` says, that compiler can't recognize command-line options. Please check compiler version, if it's supported (personally I know that gcc and clang must work fine, but I'm not sure after so long time).

**Comment by svddevelop** [comment]
> @svddevelop error (on screenshot) says, that you haven't installed PHP-CPP. Please try to install it first (or check path if already installed). Errors in `CMakeFiles/CMakeError.log` says, that compiler can't recognize command-line options. 

![image_2023-11-09_145926818](https://github.com/yaroslavche/phptdlib/assets/12089184/6a229931-5bb8-411c-9ba1-12ff8a28b7f4)

I see, that libphpcpp was compiled and installed.

>Please check compiler version, if it's supported (personally I know that gcc and clang must work fine, but I'm not sure after so long time).

`ubuntu@instance-20221110-1821:/lib$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

this is a version of VM on Oracle cloud. Need I to setup oldest version 7.3?

**Comment by yaroslavche** [comment]
@svddevelop from the old docs, I can suggest trying the following:
```
$ CONFIG=gcc CC=gcc CXX=g++ ./scripts/install.sh
```
This will clone modules into cached_builds directory, build it and install (requires sudo). Then you can always run this command for easy module updates.
After success modules installation can continue to install extension. Same way as above, just with one difference: need specify cmake flags:
```
$ cmake -D USE_SHARED_TD:BOOL=ON -D USE_SHARED_JSON:BOOL=ON -D USE_SHARED_PHPCPP:BOOL=ON ..
```
Full command list:
```
$ git clone https://github.com/yaroslavche/phptdlib.git && cd phptdlib
$ CONFIG=gcc CC=gcc CXX=g++ ./scripts/install.sh
$ mkdir build && cd build
$ cmake -D USE_SHARED_TD:BOOL=ON -D USE_SHARED_JSON:BOOL=ON -D USE_SHARED_PHPCPP:BOOL=ON ..
$ make
$ sudo make install
```

If this wouldn't help, then sorry, IDK why that happens, and you should try to find a way (it always exists). As other possible solution, you could try to use [FFI example](https://github.com/yaroslavche/phptdlib-ffi) or any other solutions.

**Comment by svddevelop** [comment]
@yaroslavche, thank you for your advise ... but it does not work too.
On the step '$ CONFIG...' going the compilation long time. At this moment the VM with the memory 1GB does not response. 
On the step 'cmake -D USE_..." shows the error:
![image_2023-11-12_115425819](https://github.com/yaroslavche/phptdlib/assets/12089184/01534e8a-6d74-4d0c-8c9b-d8faeab9de3f)



About 'FFI example': should I try to download and build [follows code](https://github.com/tdlib/td) or something other?

**Comment by yaroslavche** [comment]
The error said, that `cmakelists.txt` contains wrong td version (have 1.8.10, but actual last is 1.8.20), need to change that version in the file and retry again, it should start a build.
Also, building tdlib a pretty long process, which requires more than 1Gb RAM (IDK how many exactly, but a few years ago it was at least 2Gb+ swap, and more is better).
About ffi: that repo is exactly a working example (at least it worked well a year ago)
