### ISSUE TITLE
how to add a contact with phptdlib?

### ISSUE THREAD

**Issue by sheko016** [yaroslavche/phptdlib#78]
good morning dear.

this is to request a help to add a contact with phptdlib

I am using the following:

$obj3 = (object)[
			'phone_number' => '+584145782661', 
	        'first_name' => 'fernando', 
	        'last_name' => 'moutinho',
	        'vcard' => [],
	        'user_id' => 0];

	 $testencode = json_encode($obj3);
	 //var_dump($testencode);

    $addContact = $client->query(json_encode(['@type' => 'addContact', ['contact' => $testencode]]), 10);

but it shows me the following error message

"{"@type":"error","code":5,"message":"Contact must be non-empty","@extra":1714636915}"

I also tried the contact class
$contact = $client->query(json_encode(['@type' => 'contact', [
    	'phone_number' => '+584145782661', 
        'first_name' => 'fernando', 
        'last_name' => 'moutinho',
        'vcard' => [],
        'user_id' => 0
    ]]), 10);

but it shows me the following error message
"{"@type":"error","code":400,"message":"Failed to parse JSON object as TDLib request: Unknown class \"contact\"","@extra":1714636915}"

Please could you help me.

or make an example of how to add a contact with phptdlib

thanks greetings.

**Comment by yaroslavche** [comment]
You don't need encode twice. `query` method expecs encoded json, where `@type` and method arguments is top level keys in same array. So try to just prepare array with payload, then encode and then pass as argument. Unfortunately, I can't check code below, but I think it should work.
```php
$query = [
    '@type' => 'addContact',
    'contact' => [
        'phone_number' => '+584145782661',
        'first_name' => 'fernando',
        'last_name' => 'moutinho',
        'vcard' => '',
        'user_id' => 0,
    ],
    'share_phone_number' => true,
];
$addContact = $client->query(json_encode($query), 10);
```

**Comment by sheko016** [comment]
hello @yaroslavche  thank you very much for your prompt response.

Personally, it didn't work for me. like that.

add the contact by doing the following

```
$addContact = $client->query(json_encode(['@type' => 'importContacts', 'contacts' => [
    		[	
    			'phone_number' => '+584145782661',
    		],
    	]]), 10);
```
I have another question anyway.
**How to send a message to a newly added contact?**
but I'm going to open another thread for that question.
Thanks a lot
Greetings.

**Comment by yaroslavche** [comment]
This questions aren't related to phptdlib (and how to send message you can find in docs for this repo). Also `addContact` !== `importContact` (what you asked about). And I don't know what's wrong on your side without any output. Read the docs, please, what need to send and what you should wait in response https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1import_contacts.html

**Comment by sheko016** [comment]
Hi @yaroslavche

ok yes Mr. and if I am reading the documentation to perform all the possible tests.

Thanks a lot

Regards.
