### ISSUE TITLE
How to send a message to a newly added contact.?

### ISSUE THREAD

**Issue by sheko016** [yaroslavche/phptdlib#79]
hello @yaroslavche I hope you are very well
this is to ask the next question.

add a new contact to my telegram data with the following code

```
$addContact = $client->query(json_encode(['@type' => 'importContacts', 'contacts' => [
    		[	
    			'phone_number' => '+584145782661',
    		],
    	]]), 10);
```
the contact is saved successfully and gives me the user_id
` "{"@type":"importedContacts","user_ids":[795223843],"importer_count":[0],"@extra":719885386}"`

now I have the contact just added to my telegram.
said contact does not have a username.
at the moment I only know your user_id
what was the result that I threw when I added the contact

from my application that I am building I want to send a message to said contact just added
indicating

"Hi, I'm Deibis and I want to thank you for joining my blog."

in order to send a message I know that I must use the sendMessage class

the code would be as follows

```
$sendMesj=$client->query(json_encode([
        '@type'=>'sendMessage',
        'chat_id'=>"I don't know the chat_id only the user_id",
        'reply_to_message_id'=>0,
        'disable_notification'=>false,
        'from_background'=>false,
        'input_message_content'=>[
            '@type'=>'inputMessageText',
            'text'=>[
                '@type'=>'formattedText',
                'text'=>'Hi, I'm Deibis and I want to thank you for joining my blog.',
                'entities'=>[]
            ],
            'disable_web_page_preview'=>false,
            'clear_draft'=>false
        ]
    ]));
```

what is the problem that it presented
that in order to send a message I must know the chat_id, but when I add the contact it does not give me a chat_id, it only gives me the user_id

the question is:
**How can I send a message to a newly added contact?**

Greetings.

**Comment by yaroslavche** [comment]
I think firstly you should try to `createPrivateChat` (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_private_chat.html) which would return chat object, in which you should try to send message

**Comment by sheko016** [comment]
hello @yaroslavche
Thank you very much for your prompt reply.
Okay, I'm going to try it and then I comment on how it went for me.
again thank you very much for the information.
and sorry for the inconvenience caused.
Regards.

**Comment by yaroslavche** [comment]
[methods](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html) (which need `query` or `execute`, for example `createPrivateChat`)
[objects](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_object.html) (which you can receive in response, f.e. `chat`)

**Comment by sheko016** [comment]
hello @yaroslavche 
This is to comment that the test was 100% satisfactory
I want to thank you again for the help.
I comment here on my flow to see what you think and if you could give me some other tips

Mr the flow is as follows:

I have the phone number +584241214241
I import the contact with `importContacts`
if it returns 0 that person does not have a telegram.
If it returns an integer then that person does have a telegram and it returns the user_id of the contact.
I call all contacts with `getContacts`
Then I add the contact with its user_id with `addContact`
I call all the contacts again with `getContacts `**-> I do not understand exactly why this step should be performed (It is something like to update the DB) -> but performing that step the complete flow works for me.**
I create a private chat with the user_id with `createPrivateChat`
When I create a private chat it returns the chat_id
and finally I send the message with the chat_id with `sendMessage`

Thank you very much again for your support.

Regards.

**Comment by yaroslavche** [comment]
Looks correct to me, but this is not means, that it actually is. I don't really know all nuances, since I'm not using tdlib. Maybe i would just change one thing (if this is possible): remove `importContacts` query. Firstly check if contact by phone number exists, and if not, then `addContact`.

**Comment by sheko016** [comment]
Hi @yaroslavche

ok ok thanks.
Sorry if you are not using **tdLib** to use the telegram API that another library is using.?

and personally I did not find a way to verify if a contact exists within telegram.

Greetings.

**Comment by PapaEmeritusX** [comment]
> hello @yaroslavche This is to comment that the test was 100% satisfactory I want to thank you again for the help. I comment here on my flow to see what you think and if you could give me some other tips
> 
> Mr the flow is as follows:
> 
> I have the phone number +584241214241 I import the contact with `importContacts` if it returns 0 that person does not have a telegram. If it returns an integer then that person does have a telegram and it returns the user_id of the contact. I call all contacts with `getContacts` Then I add the contact with its user_id with `addContact` I call all the contacts again with `getContacts `**-> I do not understand exactly why this step should be performed (It is something like to update the DB) -> but performing that step the complete flow works for me.** I create a private chat with the user_id with `createPrivateChat` When I create a private chat it returns the chat_id and finally I send the message with the chat_id with `sendMessage`
> 
> Thank you very much again for your support.
> 
> Regards.

Hi, could you share a piece of code for this procedure with TdApi?
