### ISSUE TITLE
how to integrate phptdlib in laravel

### ISSUE THREAD

**Issue by sheko016** [yaroslavche/phptdlib#80]
Hello dear, I hope this is very good.

This is to ask if the phptdlib library can be integrated with laravel.

since I have been doing full tests with laravel commands but it always tells me that the class 'TDApi \ LogConfiguration' not found

It should be noted that the .php file that contains the configuration of the API_ID and HAS of telegram when I run it directly in the console if it gives me a successful connection.

but when I do a test from the laravel command it tells me class 'TDApi \ LogConfiguration' not found

Regards.

**Comment by yaroslavche** [comment]
`phptdlib` is a PHP extension and would work with any SAPI where it was enabled. It provides functions and classes, and if you faced "class not found" issue, then please check your SAPI config.
Issues section isn't a forum. If you have some troubles with make extension work - then feel free to ask. If you want to know how tdlib API works or how to use extensions in PHP - please google that. I'm closing this issue.
