### ISSUE TITLE
 setAuthenticationPhoneNumber Verify phone number timed out

### ISSUE THREAD

**Issue by tigger-te** [yaroslavche/phptdlib#94]
I run the following code and always return a timeout. I checked that my proxy settings are normal, and the proxy test using curl is also normal, but the request to verify the phone number interface always times out. The code is as follows:

$api_id = xxxx; // must be an integer
$phone_number = '+xxxxx';
$api_hash = 'd9f9633f6eaxxxxxx';

try {
    TDApi\LogConfiguration::setLogVerbosityLevel(\TDApi\LogConfiguration::LVL_ERROR);

    $client = new TDLib\JsonClient();

    $tdlibParams = new TDApi\TDLibParameters();
    $tdlibParams
        ->setParameter(TDApi\TDLibParameters::USE_TEST_DC, false)
        ->setParameter(TDApi\TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDApi\TDLibParameters::USE_FILE_DATABASE, true)
        ->setParameter(TDApi\TDLibParameters::USE_CHAT_INFO_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_MESSAGE_DATABASE, false)
        ->setParameter(TDApi\TDLibParameters::USE_SECRET_CHATS, false)
        ->setParameter(TDApi\TDLibParameters::API_ID, $api_id)
        ->setParameter(TDApi\TDLibParameters::API_HASH, $api_hash)
        ->setParameter(TDApi\TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
        ->setParameter(TDApi\TDLibParameters::DEVICE_MODEL, php_uname('s'))
        ->setParameter(TDApi\TDLibParameters::SYSTEM_VERSION, php_uname('v'))
        ->setParameter(TDApi\TDLibParameters::APPLICATION_VERSION, '0.0.10')
        ->setParameter(TDApi\TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
        ->setParameter(TDApi\TDLibParameters::IGNORE_FILE_NAMES, false);
	//var_dump($tdlibParams);die;
    $result = $client->setTdlibParameters($tdlibParams);
	
    $result = $client->setDatabaseEncryptionKey(); // checkDatabaseEncryptionKey(key) or DESTROY
	
    // UNCOMMENT NEXT and COMMENT PREVIOUS LINES WHEN RECEIVE SMS. Set your data
    // $result = $client->query(json_encode(['@type' => 'checkAuthenticationCode', 'code' => 'xxxxx', 'first_name' => 'dummy', 'last_name' => 'dummy']), 10);
   
	// var_dump($result);die;
	$proxy = [
		'@type' => 'proxyTypeSocks5',
		 'username' => '',
         'password' => '',

   ];

	$res = $client->query(json_encode([
		'@type' => 'addProxy',
		'server' => 'xxxxxx',
		'port' => 1080,
		'enable' => true,
		'type' => $proxy
	]), 10);
	 //var_dump($res);die;
	$query = json_encode([
		'@type' => 'setAuthenticationPhoneNumber',
		'phone_number' => $phone_number,
	]);
   // $r=$client->setDefaultTimeout(30);

	$result = $client->query($query,60);
	var_dump($result);die;

The error log is as follows:

PHP Fatal error:  Uncaught Exception: Timeout waiting for response in /home/wwwroot/default/send.php:53
Stack trace:
#0 /home/wwwroot/default/send.php(53): TDLib\JsonClient->query('{"@type":"setAu...', 3)
#1 {main}
  thrown in /home/wwwroot/default/send.php on line 53

Fatal error: Uncaught Exception: Timeout waiting for response in /home/wwwroot/default/send.php:53
Stack trace:
#0 /home/wwwroot/default/send.php(53): TDLib\JsonClient->query('{"@type":"setAu...', 3)
#1 {main}
  thrown in /home/wwwroot/default/send.php on line 53

**Comment by tigger-te** [comment]
Run process debugging, these errors occur：

[ 4][t 4][1631983502.721729278][BufferedFd.h:198][#1][!Socks5]	Flush read: +10B[total:10B]
[ 4][t 4][1631983502.721859216][Socks5.cpp:126][#1][!Socks5][&proxy]	Receive IP address response of size 10
[ 4][t 4][1631983502.721912860][TransparentProxy.cpp:37][#1][!Socks5][&proxy]	Finish to connect to proxy
[ 3][t 4][1631983502.722311973][ConnectionCreator.cpp:1005][#1][!ConnectionCreator][&connections]	Start check: Socks5 [192.168.43.125:1080] --> [149.154.167.40:443] to DcId{2} from [192.168.228.133:44436] without auth data
[ 3][t 0][1631983502.722314357][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 0.000000
[ 3][t 0][1631983502.722423076][Client.cpp:284][&td_requests]	End to wait for updates, returning object 0 (nil)
[ 3][t 4][1631983502.722641229][StateManager.cpp:146][#1][!State manager]	Auto set net_type = Other
[ 3][t 4][1631983502.722717523][ConnectionCreator.cpp:550][#1][!ConnectionCreator][&connections]	Receive network flag true with generation 2
[ 3][t 4][1631983502.722758293][ConnectionCreator.cpp:555][#1][!ConnectionCreator][&connections]	Set proxy query token to 0: 2 2
[ 3][t 4][1631983502.722819328][ConnectionCreator.cpp:845][#1][!ConnectionCreator][&connections]	In client_loop: [client:0xe4ec204da606b639]
[ 3][t 4][1631983502.722950935][ConfigManager.cpp:762][#1][!Recoverer][&config_recoverer]	Failed to connect for 0.067274
[ 3][t 4][1631983502.723063230][ConfigManager.cpp:835][#1][!Recoverer][&config_recoverer]	Wakeup in 19.9s
[ 3][t 4][1631983502.723510026][RawConnection.cpp:88][#1][!PingActor<Socks5 [192.168.43.125:1080] --> [149.154.167.40:443] to DcId{2} from [192.168.228.133:44436]>]	Send handshake packet: 
00000000 00000000 00000001 00000000 00000030 be7e8ef1 329f7b48 4c771367 4ddb6ef3 045b5d8e 5e9457cd 2018969d 39fd5a78 e084a40b c9435980 1b3c6bf9
3c16344c
[ 4][t 4][1631983502.724474191][BufferedFd.h:207][#1][!PingActor<Socks5 [192.168.43.125:1080] --> [149.154.167.40:443] to DcId{2} from [192.168.228.133:44436]>]	Flush write: +136B[left:0B]

I have been debugging this problem for a few days, please help me

**Comment by yaroslavche** [comment]
Please try to uncomment default timeout before `setAuthenticationPhoneNumber`. 
```
$client->setDefaultTimeout(3);
```
[Here](https://github.com/yaroslavche/phptdlib/issues/26) you can find a similar issue with more details.

**Comment by tigger-te** [comment]
This has been tested, the result is still the same，The code is as follows:
$res = $client->query(json_encode([
	'@type' => 'addProxy',
	'server' => 'xxxxxx',
	'port' => 1080,
	'enable' => true,
	'type' => $proxy
]), 10);

	$query = json_encode([
		'@type' => 'setAuthenticationPhoneNumber',
		'phone_number' => (string)$phone_number,
	]);
    $result=$client->setDefaultTimeout(5);

	$result = $client->query($query,1);
	var_dump($result);die;	
//$result = $client->setAuthenticationPhoneNumber($phone_number, 3);

Error log :

PHP Fatal error:  Uncaught Exception: Timeout waiting for response in /home/wwwroot/default/send.php:53
Stack trace:
#0 /home/wwwroot/default/send.php(53): TDLib\JsonClient->query('{"@type":"setAu...', 1)
#1 {main}
  thrown in /home/wwwroot/default/send.php on line 53

Fatal error: Uncaught Exception: Timeout waiting for response in /home/wwwroot/default/send.php:53
Stack trace:
#0 /home/wwwroot/default/send.php(53): TDLib\JsonClient->query('{"@type":"setAu...', 1)
#1 {main}
  thrown in /home/wwwroot/default/send.php on line 53
 
You can see the same error

**Comment by yaroslavche** [comment]
I can't see, what is in `send.php` on line `53` (but I beleive that is `$result = $client->query($query,1);`). Also it looks to me, that you have some mess in code (actually because looks like you're using different approaches. yes, I know about mess in this repo docs =) ). So please try following simple example:
```php
<?php

use TDApi\LogConfiguration;
use TDApi\TDLibParameters;
use TDLib\JsonClient;

error_reporting(E_ALL);
ini_set('display_errors', '1');

$api_id = 11111;
$api_hash = 'abcdef1234567890abcdef1234567890';
$phone_number = '+380991234567';

try {
    LogConfiguration::setLogVerbosityLevel(LogConfiguration::LVL_ERROR);

    $client = new JsonClient();

    $tdlibParams = new TDLibParameters();
    $tdlibParams
        ->setParameter(TDLibParameters::USE_TEST_DC, true)
        ->setParameter(TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
        ->setParameter(TDLibParameters::USE_FILE_DATABASE, false)
        ->setParameter(TDLibParameters::USE_CHAT_INFO_DATABASE, false)
        ->setParameter(TDLibParameters::USE_MESSAGE_DATABASE, false)
        ->setParameter(TDLibParameters::USE_SECRET_CHATS, false)
        ->setParameter(TDLibParameters::API_ID, $api_id)
        ->setParameter(TDLibParameters::API_HASH, $api_hash)
        ->setParameter(TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
        ->setParameter(TDLibParameters::DEVICE_MODEL, php_uname('s'))
        ->setParameter(TDLibParameters::SYSTEM_VERSION, php_uname('v'))
        ->setParameter(TDLibParameters::APPLICATION_VERSION, '0.0.10')
        ->setParameter(TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
        ->setParameter(TDLibParameters::IGNORE_FILE_NAMES, false);
    $client->setTdlibParameters($tdlibParams);
    $client->setDatabaseEncryptionKey();
    $client->setDefaultTimeout(3);
    $result = $client->setAuthenticationPhoneNumber($phone_number);
    var_dump($result);
} catch (Exception $exception) {
    echo sprintf('something goes wrong: %s', $exception->getMessage());
}
```
You should be sure, that timeout comes from authenticationPhoneNumber query. Are you sure, that is not because added proxy with timeout 0? From your logs I can see, that all should work fine, and maybe try to set default timeout before any action with client (including proxy). Also probably it worth to check [tdlib docs](https://core.telegram.org/tdlib/getting-started)

**Comment by tigger-te** [comment]
I try

**Comment by tigger-te** [comment]
Thank you for your reply ，Run the example you provided and return the same error：
something goes wrong: Timeout waiting for response

The full code send.php:
```
<?php

Error_Reporting(E_ALL);
ini_set('display_errors', 1);

$client = new \TDLib\JsonClient();
$chat_id=-xxxxxx;
$api_id = xxxxx; // must be an integer
$phone_number = '+xxxx';
$api_hash = 'xxxxxx';
$message_text = 'hello';
$print_timeout = 1;
$tdlibParams = new \TDApi\TDLibParameters();
$tdlibParams
->setParameter(\TDApi\TDLibParameters::USE_TEST_DC, true)
->setParameter(\TDApi\TDLibParameters::DATABASE_DIRECTORY, '/var/tmp/tdlib')
->setParameter(\TDApi\TDLibParameters::FILES_DIRECTORY, '/var/tmp/tdlib')
->setParameter(\TDApi\TDLibParameters::USE_FILE_DATABASE, false)
->setParameter(\TDApi\TDLibParameters::USE_CHAT_INFO_DATABASE, false)
->setParameter(\TDApi\TDLibParameters::USE_MESSAGE_DATABASE, false)
->setParameter(\TDApi\TDLibParameters::USE_SECRET_CHATS, false)
->setParameter(\TDApi\TDLibParameters::API_ID, $api_id)
->setParameter(\TDApi\TDLibParameters::API_HASH, $api_hash)
->setParameter(\TDApi\TDLibParameters::SYSTEM_LANGUAGE_CODE, 'en')
->setParameter(\TDApi\TDLibParameters::DEVICE_MODEL, php_uname('s'))
->setParameter(\TDApi\TDLibParameters::SYSTEM_VERSION, php_uname('v'))
->setParameter(\TDApi\TDLibParameters::APPLICATION_VERSION, '0.0.10')
->setParameter(\TDApi\TDLibParameters::ENABLE_STORAGE_OPTIMIZER, true)
->setParameter(\TDApi\TDLibParameters::IGNORE_FILE_NAMES, false);

$result = $client->setTdlibParameters($tdlibParams);

$result = $client->setDatabaseEncryptionKey();
$state = $client->getAuthorizationState();
$proxy = [
		'@type' => 'proxyTypeSocks5',
		 'username' => '',
		 'password' => '',

   ];

$res = $client->query(json_encode([
	'@type' => 'addProxy',
	'server' => '192.168.43.125',
	'port' => 1080,
	'enable' => true,
	'type' => $proxy
]), 10);

$query = json_encode([
	'@type' => 'setAuthenticationPhoneNumber',
	'phone_number' => (string)$phone_number,
]);
$result = $client->query($query,5);
var_dump($result);	
$r=$client->query(json_encode([
    '@type'=>'openChat',
    'chat_id'=>$chat_id
]));

$client->query(json_encode([
    '@type'   => 'sendChatAction',
    'chat_id' => $chat_id,
    'action'  => [
        '@type' => 'chatActionTyping'
    ]
]));


sleep(1);

$$client->query(json_encode([
    '@type'   => 'sendChatAction',
    'chat_id' => $chat_id,
    'action'  => [
        '@type' => 'chatActionCancel'
    ]
]));


$res=$client->query(json_encode([
    '@type'=>'sendMessage',
    'chat_id'=>$chat_id,
    'reply_to_message_id'=>0,
    'disable_notification'=>false,
    'from_background'=>false,
    'input_message_content'=>[
        '@type'=>'inputMessageText',
        'text'=>[
            '@type'=>'formattedText',
            'text'=>$message_text,
            'entities'=>[]
        ],
        'disable_web_page_preview'=>false,
        'clear_draft'=>false
    ]
]));

$client->query(json_encode([
    '@type'   => 'closeChat',
    'chat_id' => $chat_id
]));

```


You can see that I set the timeout time in the query function to 10 seconds
I request setAuthenticationPhoneNumber verification after proxy settings. According to the official document, I must pass the setAuthenticationPhoneNumber verification before I can use other API, such as sending messages and joining groups.

**Comment by yaroslavche** [comment]
```php
$client->setDefaultTimeout(3);
```
is important. This is default timeout for all the queries. Even for query to setting up the proxy.
I think that timeout can be because of proxy, but I can't say what was wrong. You should check what is your authorization state, what responses you have, enable log, see what happened in tdlib output. All of the details you can find in tdlib docs.
Before sending a message you should be sure, that authorizationState equals `authorizationStateReady`. Start from smaller steps and debug them. Timeout means that you have some issues with connection. I can't know which ones, so sorry, can't help =)

**Comment by tigger-te** [comment]
Yes, I also think it is a connection problem, but I tested the socket proxy with curl in send.php, the result is normal, but it can't run in tdlib. I posted this part of the link error in the error log above.
Socket test example：
---
    // $ch = curl_init(); 
	// curl_setopt($ch, CURLOPT_PROXY, '192.168.43.125:1080');
	// curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
	// curl_setopt($ch, CURLOPT_URL, 'https://www.google.com/');
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	// curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
	// curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
	// curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
	// curl_setopt($ch, CURLOPT_TIMEOUT, 30);
	// curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
 
	
	// $result = curl_exec($ch);	
	// if($result){
		// echo "success";
	// }else{
		// echo "fail";
	// }
	
	// curl_close($ch);
---
 run result success
The error log posted for the first time contains this：
[ 3][t 4][1631983502.722950935][ConfigManager.cpp:762][#1][!Recoverer][&config_recoverer] Failed to connect for 0.067274
[ 3][t 4][1631983502.723063230][ConfigManager.cpp:835][#1][!Recoverer][&config_recoverer] Wakeup in 19.9s
[ 3][t 4][1631983502.723510026][RawConnection.cpp:88][#1][!PingActor<Socks5 [192.168.43.125:1080] --> [149.154.167.40:443] to DcId{2} from [192.168.228.133:44436]>] Send handshake packet:
00000000 00000000 00000001 00000000 00000030 be7e8ef1 329f7b48 4c771367 4ddb6ef3 045b5d8e 5e9457cd 2018969d 39fd5a78 e084a40b c9435980 1b3c6bf9
3c16344c
[ 4][t 4][1631983502.724474191][BufferedFd.h:207][#1][!PingActor<Socks5 [192.168.43.125:1080] --> [149.154.167.40:443] to DcId{2} from [192.168.228.133:44436]>] Flush write: +136B[left:0B]

The connection problem should be here
